[project]
name = "chesspuzzle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.40.0",
]

[tool.setuptools.packages.find]
include = ["chesspuzzle*"]

[tool.setuptools.package-data]
"chesspuzzle.components" = ["assets/*.js"]
